# Generated by Django 6.0 on 2026-01-08 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_alter_escrow_status_alter_order_created_at_and_more'),
        ('escrow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='contract',
        ),
        migrations.CreateModel(
            name='EscrowTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escrow_id', models.CharField(db_index=True, help_text='Escrow.com transaction ID', max_length=255, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total transaction amount', max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, help_text='Platform commission (20%)', max_digits=10)),
                ('freelancer_amount', models.DecimalField(decimal_places=2, help_text='Freelancer payout (80%)', max_digits=10)),
                ('currency', models.CharField(default='USD', help_text='Currency code (ISO 4217)', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending - Awaiting Payment'), ('FUNDED', 'Funded - Payment Received'), ('SHIPPING', 'Work Delivered - Awaiting Approval'), ('DISBURSED', 'Disbursed - Funds Released'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded to Client'), ('DISPUTED', 'Under Dispute')], db_index=True, default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('funded_at', models.DateTimeField(blank=True, null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('escrow_response', models.JSONField(blank=True, default=dict, help_text='Full response from Escrow API')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this transaction')),
                ('client', models.ForeignKey(help_text='Client who is paying', on_delete=django.db.models.deletion.PROTECT, related_name='client_escrow_transactions', to=settings.AUTH_USER_MODEL)),
                ('freelancer', models.ForeignKey(help_text='Freelancer who will receive payment', on_delete=django.db.models.deletion.PROTECT, related_name='freelancer_escrow_transactions', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(help_text='Associated order', on_delete=django.db.models.deletion.PROTECT, related_name='escrow_transaction', to='Order.order')),
            ],
            options={
                'verbose_name': 'Escrow Transaction',
                'verbose_name_plural': 'Escrow Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EscrowWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(help_text='Webhook event type', max_length=100)),
                ('payload', models.JSONField(help_text='Full webhook payload')),
                ('signature', models.CharField(blank=True, help_text='Webhook signature for verification', max_length=255)),
                ('signature_valid', models.BooleanField(default=False, help_text='Whether signature verification passed')),
                ('processed', models.BooleanField(default=False, help_text='Whether this webhook has been processed')),
                ('processing_error', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('escrow_transaction', models.ForeignKey(blank=True, help_text='Associated escrow transaction (if identifiable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_logs', to='escrow.escrowtransaction')),
            ],
            options={
                'verbose_name': 'Escrow Webhook Log',
                'verbose_name_plural': 'Escrow Webhook Logs',
                'ordering': ['-received_at'],
            },
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='Milestone',
        ),
        migrations.AddIndex(
            model_name='escrowtransaction',
            index=models.Index(fields=['status', 'created_at'], name='escrow_escr_status_2d85b0_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowtransaction',
            index=models.Index(fields=['client', 'status'], name='escrow_escr_client__c4ec2d_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowtransaction',
            index=models.Index(fields=['freelancer', 'status'], name='escrow_escr_freelan_126fae_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowtransaction',
            index=models.Index(fields=['escrow_id'], name='escrow_escr_escrow__2bf956_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowwebhooklog',
            index=models.Index(fields=['event_type', 'received_at'], name='escrow_escr_event_t_06eb9c_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowwebhooklog',
            index=models.Index(fields=['processed', 'received_at'], name='escrow_escr_process_65e699_idx'),
        ),
    ]
