# Generated by Django 6.0 on 2026-05-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0024_user_is_email_verified_user_is_phone_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_earnings',
            field=models.BooleanField(default=True, help_text='Determine if earnings are shown on public profile'),
        ),
    ]
